### ISSUE TITLE
Issues in mod creation / edit page (for beta)

### ISSUE THREAD

**Issue by Minenash** [modrinth/code#2105]
So this is what I've found so far:

**All the issues not marked as solve in this issue, was split into other issues. Don't update these checkboxes**

General:

- [ ] Categories drop-down not as long as the fields above/below it (now modrinth/code#2053)
- [x] ~~On linux using firefox can't drag files to the icon's "choose image or drag it here"~~
- [ ] All the drop-downs but supported environments are lowercase, while supported environments are uppercase. However, when you go to edit, the selected options for supported environments are lowercase, but all the options are still capitalistic (now modrinth/code#2052)
- [ ] **New**: When you click reset icon, the file selector still says 1 file selected (now modrinth/code#2051)
- [x] **New**: The "Edit Mod" / "Create mod" header has a huge amount of padding and a small save/create button. It just feels very off. It's also inconsistent with the dashboard's header scale.

Description:

- [ ] With how focusing works, the box probably shouldn't be a grey box when unselected.
- [ ] Due to the limited with, while the markdown preview is nice, it isn't a great way to actually see what it'll look like to people. A "preview" button that would allow you to see how the page will look without officially creating the mod would be very useful. Though this should probably be it's own issue.
- [x] The link to the markdown formatting guide isn't colored nor underlined
- [x] Should say somewhere that non script/iframe html tags are also supported.

Versions:

- [x] - ~~Can't upload files †~~
- [x] - Version names just don't show
- [x] - `Add a version` button should have more spacing between it and the "Upload Versions" title
- [x] - Status is blank
- [x] - There probably should be a title above the remove/edit buttons. Maybe "Actions"
- [x] - When version names were showing, the space allocated to them were minimal, while mod loader has a huge amount of space.
- [ ] - There's no checkbox for showing/not showing snapshot versions (now modrinth/code#2050)
- [x] - No way to edit a version after it's been published

Edit-specific:

- [x] - License url is gone
- [x] - Can't manage version is edit screen
- [x] - ~~Description isn't saved~~

~~† So it might be uploading, but since there was a (I think fixed) problem with being unable to create a mod with a version, I didn't have any versions to have files in. In the version creation screen on the versions page of the mod, it also shows that no file is selected, but after it was approved there was in fact a file~~
