### ISSUE TITLE
Stop user from interacting with mods when minecraft is running

### ISSUE THREAD

**Issue by denisJaved** [modrinth/code#2445]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

App

### Is your suggested feature related to a problem? Please describe.

Obviously it is impossible to remove/disable mod when instance(minecraft) is running.
But theese buttons always will try to remove/disable mod when pressed.

### Describe the solution you'd like

Disable buttons for disabling/enabling/updating/removing mod when minecraft is running.

Like this:
![image](https://github.com/user-attachments/assets/ada533d0-651c-4943-afa2-2bac638ca84c)
this done by adding `disabled` attribute to switch's input tag and buttons.

### Describe alternatives you've considered

Before disabling/enabling/updating/removing check is minecraft running right now and if it is show user confirmation prompt.
![image](https://github.com/user-attachments/assets/0524dbf2-d7cf-44f1-9655-d5afc09e3ae8)

## Tasks

- [ ] Implementation in fork repo (doing right now)
- [ ] Discord thread
- [ ] Pull request

**Comment by denisJaved** [comment]
Limitation caused by Minecraft. Modloaders gather mods only on startup. Which means even if you would change mod file, nothing will happen until you restart game

**Comment by Felix14-v2** [comment]
> Limitation caused by Minecraft

It doesn't. The issue is an inability to remove a mod file after the game launch, not the inability to "unmodify" the game on the fly.

**Comment by denisJaved** [comment]
> > Limitation caused by Minecraft
> 
> It doesn't. The issue is an inability to remove a mod file after the game launch, not the inability to "unmodify" the game on the fly.

I know, but still you can't remove mod from game without restarting game.
Anyways both of our points are right.

**Comment by Felix14-v2** [comment]
Anyways, that's an unrelated issue.
